sudo: required
language: bash
dist: trusty
install:
    - ./install.sh
before_script:
    - scripts/download_data.sh
    - cd include; make; cd -;
script:
    - scripts/create_mod_files.sh data/out
    - cd include; ./demand_test; cd -;
