
all: demand_test demand_test_jam

demand_test: demand.hpp demand_test.cpp
	g++ -std=c++11 -Wall demand_test.cpp -o demand_test -g

demand_test_jam: demand.hpp demand_test_jam.cpp
	g++ -std=c++11 -Wall demand_test_jam.cpp -o demand_test_jam -g
